### ISSUE TITLE
`black` is failing in tests

### ISSUE THREAD

**Issue by cnpryer** [pola-rs/polars-book#133]
## Problem

As mentioned on Discord

```log
Run black --check .
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/__init__.py)
```

Documenting this to either pick up myself or for someone else to grab it before me.

## Solution

TBD

**Comment by cnpryer** [comment]
#134
